### ISSUE TITLE
文章貌似存在误导的部分

### ISSUE THREAD

**Issue by Zephylaci** [Haixiang6123/learn-error-bounday#1]
文章写的很好，诙谐易懂，但看完后有一处我稍微有些疑问。  
关于这一行的作用<https://github.com/haixiangyan/my-react-error-bounday/blob/84317897eda1d6b74c460eb47f526bd68d4a34b2/src/lib/ErrorBoundary.tsx#L68>. 
文章里说这里是针对数组和对象的值是否真的有改变加的额外判断  
但首先，函数和对象如果引用发生改变，Object.is 是可以判断到的，这里如果值发生了改变引用应该会变化才是。
其次，从命名上看，这是一个状态回调函数，同时这里没有针对这个函数的返回值做任何处理
我一度以为这里会有什么魔法，于是我拉下跑了下，还是没弄明白这个函数具体的作用
最后我去看了
react-error-boundary的说明
<https://github.com/bvaughn/react-error-boundary/blob/a0a370c7fe145e5cf169063eb4b7ff1a059fd84c/README.md?plain=1#L274>
似乎是针对resetkey变更时调用reset，但是不会有onRest的回调的一种处理，没细看，这么设计也许是为了避免一些业务场景的循环调用，但总之应该不是文章中描述的那样

**Comment by haixiangyan** [comment]
当时看这个 `onResetKeysChange` 也是用来处理一些 Edge Case 的场景。确实如你所说，不应该写成 “用来判断引用是否改变”，估计写的时候脑子不太好使🥲
